---
label: Definições config.yml
hide_body: true
fields:
- type: text
  name: title
  label: Título do Website
  description: Utilizado para SEO. Por exemplo, aparece no nome do separador.
- type: textarea
  name: description
  label: Descrição do Website
  description: A descrição do website é usada para SEO, e aparece na descrição do
    Google e publicações sempre que alguém partilha o link do site (e.g. Facebook)
- type: text
  name: baseurl
  label: URL
  description: O URL do website
- type: text
  name: url
  label: url
- type: boolean
  name: use_authors
  label: Utilizar autores
  description: Se devem aparecer quais os autores dos artigos ou se deve ser anónimo.
- type: file
  name: brand_logo
  label: Logótipo
- type: text
  name: brand_name
  label: brand_name
- type: text
  name: header
  label: Texto principal
  description: O texto principal que aparece debaixo do logótipo em grande.
- type: text
  name: subheader
  label: Texto secundário
  description: O texto secundário mais pequeno que aparece debaixo do texto principal.
- type: file
  name: meta_image
  label: meta_image
- type: text
  name: twitter_username
  label: Nome de utilizador Twitter
- type: text
  name: facebook_page
  label: 'Página de Facebook '
  description: O nome que aparece no URL da página.<br>
- type: text
  name: email
  label: Email
- type: text
  name: linkedin_page
  label: URL Página Linkedin
  description: O URL completo para a página LinkedIn.
- type: text
  name: instagram_username
  label: Nome de utilizador Instagram
  description: O nome de utilizador do Instagram.
- type: number
  name: whatsapp_number
  label: Número Whatsapp
  description: 'O número WhatsApp com o indicativo do país em prefixo.<br>Exemplo:
    35191xxxxxxx'
- type: text
  name: help_one_title
  label: Título Secção Lado Esquerdo
- type: text
  name: help_one_content
  label: Conteúdo Secção Lado Esquerdo
- type: text
  name: help_one_button
  label: Título Botão Lado Esquerdo
- type: text
  name: help_one_link
  label: Link Botão Lado Esquerdo
- type: text
  name: help_two_title
  label: Título Secção Lado Central
- type: text
  name: help_two_content
  label: Conteúdo Secção Lado Central
- type: text
  name: help_two_button
  label: Título Botão Central
- type: text
  name: help_two_link
  label: Link Botão Central
- type: text
  name: help_three_title
  label: Titulo Botão Lado Direito
- type: text
  name: help_three_content
  label: Conteúdo Secção Lado Direito
- type: text
  name: help_three_button
  label: Titulo Botão Lado Direito
- type: text
  name: help_three_link
  label: Link Botão Lado Direito
