---
label: Definições config.yml
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: text
  name: baseurl
  label: baseurl
- type: text
  name: url
  label: url
- type: text
  name: permalink
  label: permalink
- type: text
  name: content_type
  label: content_type
- type: boolean
  name: use_authors
  label: use_authors
- type: file
  name: brand_logo
  label: brand_logo
- type: text
  name: brand_name
  label: brand_name
- type: text
  name: header
  label: header
- type: text
  name: subheader
  label: subheader
- type: file
  name: meta_image
  label: meta_image
- type: text
  name: twitter_username
  label: twitter_username
- type: text
  name: facebook_page
  label: facebook_page
- type: text
  name: github_username
  label: github_username
- type: text
  name: email
  label: email
- type: text
  name: linkedin_page
  label: linkedin_page
- type: text
  name: instagram_username
  label: instagram_username
- type: number
  name: whatsapp_number
  label: whatsapp_number
- type: text
  name: help_one_title
  label: help_one_title
- type: text
  name: help_one_content
  label: help_one_content
- type: text
  name: help_one_button
  label: help_one_button
- type: text
  name: help_one_link
  label: help_one_link
- type: text
  name: help_two_title
  label: help_two_title
- type: text
  name: help_two_content
  label: help_two_content
- type: text
  name: help_two_button
  label: help_two_button
- type: text
  name: help_two_link
  label: help_two_link
- type: text
  name: help_three_title
  label: help_three_title
- type: text
  name: help_three_content
  label: help_three_content
- type: text
  name: help_three_button
  label: help_three_button
- type: text
  name: help_three_link
  label: help_three_link
- type: text
  name: theme
  label: theme
- type: list
  name: plugins
  label: plugins
- type: field_group
  name: sass
  label: sass
  fields:
  - type: text
    name: sass_dir
    label: sass_dir
  - type: text
    name: style
    label: style
